defaults:
  - _self_
  - camera
  - fisheyecamera
  - network
  - keypoint
  - oculus
  - robot: allegro_kinova
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

record_realsense: true
record_fisheye: true # fish eye meaning RGB
storage_path: <data-path>
demo_num: <demo-num>

hydra:
  output_subdir:
  run:
    dir: .
