defaults:
  - _self_
  - camera
  - fisheyecamera
  - network
  - keypoint
  - oculus
  - robot: allegro_kinova
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

record_realsense: true
record_fisheye: true # fish eye meaning RGB
record_spacemouse: false
storage_path: /data/irmak/third_person_manipulation/plug_insertion
demo_num: 1

hydra:
  output_subdir:
  run:
    dir: .
